name: Docker Builder CI

# Reference:
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on: [push, pull_request, workflow_dispatch]

# https://github.com/docker/build-push-action
jobs:

  # https://github.com/docker/build-push-action/issues/225
  docker:
    name: "Build Docker image develop"
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.5
    # https://github.com/docker/build-push-action/blob/master/docs/advanced/tags-labels.md
    - name: Docker meta
      id: meta
      uses: crazy-max/ghaction-docker-meta@v3.6.0
      with:
        images: nanosaur/isaac_ros
        # generate Docker tags based on the following events/attributes
        tags: |
          type=ref,event=branch
          type=semver,pattern={{version}}
          type=ref,event=tag
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1.14.0 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2.7.0
      with:
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Docker Image digest
      run: |
        echo ${{ steps.docker_build.outputs.digest }}

  # https://github.com/peter-evans/dockerhub-description
  update_docker_description:
    name: Update docker description
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.5
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: nanosaur/isaac_ros
        short-description: ${{ github.event.repository.description }}
        readme-filepath: ./README.md

  notify:
    name: "Notify socials"
    needs: [update_docker_description]
    runs-on: ubuntu-latest #self-hosted
    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'The project **{{ EVENT_PAYLOAD.repository.full_name }}** has been deployed v${{ steps.meta.outputs.tags }}.'